/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'surface-bright': '#f7f9fc',
        'inverse-surface': '#2d3133',
        'surface-container': '#eceef1',
        'inverse-primary': '#a9c7ff',
        'on-secondary-fixed-variant': '#005230',
        'surface-dim': '#d8dadd',
        'on-error': '#ffffff',
        'on-primary-container': '#b3cdff',
        'outline-variant': '#c2c6d3',
        secondary: '#036d42',
        'inverse-on-surface': '#eff1f4',
        'on-surface': '#191c1e',
        'surface-container-high': '#e6e8eb',
        surface: '#f7f9fc',
        'on-background': '#191c1e',
        'on-primary-fixed': '#001b3d',
        'primary-container': '#1a56a0',
        error: '#ba1a1a',
        'on-tertiary-container': '#ffc179',
        'on-tertiary-fixed': '#2b1700',
        'on-tertiary-fixed-variant': '#663e00',
        'surface-container-highest': '#e0e3e6',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#002111',
        'error-container': '#ffdad6',
        'tertiary-container': '#7c4c00',
        'tertiary-fixed': '#ffddb9',
        tertiary: '#5c3700',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#0d7146',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#ffb964',
        'secondary-fixed-dim': '#81d8a4',
        primary: '#003e7e',
        'primary-fixed': '#d6e3ff',
        outline: '#737782',
        'on-surface-variant': '#424751',
        'surface-container-low': '#f2f4f7',
        'secondary-container': '#9af2bc',
        'on-primary-fixed-variant': '#00468c',
        background: '#f7f9fc',
        'on-error-container': '#93000a',
        'secondary-fixed': '#9df5bf',
        'surface-tint': '#265ea8',
        'surface-variant': '#e0e3e6',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
}